name: Build widget

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - widget
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.6
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true

    - name: Create widget
      run: node index.js
      env: 
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    - name: Commit and push
      run: |-
        git diff
        git config --global user.email "37860569+Minh-Ton@users.noreply.github.com"
        git config --global user.name "not-minh"
        git add -A
        git commit -m "Regenerate widget" || exit 0
        git push
